### ISSUE TITLE
fstype flag modification

### ISSUE THREAD

**Issue by n7s** [silnrsi/font-awami#1] opened 2018-02-14 11:17 UTC
Just noticing (from reports in the CI) that the fstype ([embedding permissions](https://www.microsoft.com/typography/otspec/os2.htm#fst)) probably needs changing from 4 (Preview & Print embedding) to 0.

**Comment by bobh0303** [comment] 2018-02-14 15:05
This may be a defect in our workflow which currently recommends removing `openTypeOS2Type` from fontinfo. The assumption is that the resulting fsType will be zero -- but it may be that assumption is invalid. Will investigate.

**Comment by bobh0303** [comment] 2018-02-14 18:29
The root cause is that `psfglyphs2ufo` (used by `preflightg`) is removing the `openTypeOS2Type` key from the UFO and it shouldn't. 

see https://github.com/silnrsi/pysilfont/issues/52

**Comment by bobh0303** [comment] 2018-03-13 21:25
fixed by https://github.com/silnrsi/font-awami/commit/1390a2db574fe12e5aea9c59e508c9c10ea82187 and https://github.com/silnrsi/pysilfont/commit/2d162a46e954daccd63d76afb4716ad4c355953b

See also ABS-1479

**Closed by bobh0303** 2018-03-13 21:25 UTC
